INSERT INTO "ARTICULO" ("ID_ARTICULO", "CODIGO", "DESCRIPCION", "ID_COLOR", "ID_MEDIDA", "ID_ARTICULO_PRECIO", "ID_SUBFAMILIA", "ID_FABRICANTE") VALUES(
    1,
    "CODIGO",
    "DESCRIPCION",
    1,
    1,
    1,
    1,
    1
)