DELETE FROM public."FACTURA";
DELETE FROM public."FACTURA_ARTICULO";
DELETE FROM public."PRODUCCION_ARTICULO";
DELETE FROM public."PEDIDO_PRODUCCION";
DELETE FROM public."PRESUPUESTO";
DELETE FROM public."ARTICULO_PRESUPUESTO";
DELETE FROM public."INGRESO";
DELETE FROM public."ARTICULO_INGRESO";




