SELECT AR.* ,
MD."CODIGO" AS MEDIDA_CODIGO, MD."DESCRIPCION" AS MEDIDA_DESCRIPCION, 
FM."CODIGO" AS FAMILIA_CODIGO, FM."DESCRIPCION" AS FAMILIA_DESCRIPCION,
CL."CODIGO" AS COLOR_CODIGO, CL."DESCRIPCION" AS COLOR_DESCRIPCION 
FROM "ARTICULO" AR,"MEDIDA" MD, "FAMILIA" FM, "COLOR" CL 
WHERE AR."ID_MEDIDA"= MD."ID_MEDIDA" AND 
AR."ID_FAMILIA"= FM."ID_FAMILIA" AND 
AR."ID_COLOR"= CL."ID_COLOR" AND 
FM."CODIGO"='CALA' AND MD."CODIGO" ='S'

SELECT AR.*, 
MD."CODIGO" AS MEDIDA_CODIGO, MD."DESCRIPCION" AS MEDIDA_DESCRIPCION,
FM."CODIGO" AS FAMILIA_CODIGO, FM."DESCRIPCION" AS FAMILIA_DESCRIPCION
FROM "ARTICULO" AR,"MEDIDA" MD, "FAMILIA" FM, "COLOR" CL 
WHERE AR."ID_MEDIDA"= MD."ID_MEDIDA" AND 
AR."ID_FAMILIA"= FM."ID_FAMILIA" AND 
AR."ID_COLOR"= CL."ID_COLOR" AND 
FM."CODIGO"='CALA' AND MD."CODIGO" ='S'

SELECT 
FM."CODIGO" || '\' || MD."CODIGO" AS MODELO, AR."PRECIO1", CL."DESCRIPCION"
FROM "ARTICULO" AR,"MEDIDA" MD, "FAMILIA" FM, "COLOR" CL
WHERE 
AR."ID_MEDIDA"= MD."ID_MEDIDA" AND
AR."ID_FAMILIA"= FM."ID_FAMILIA" AND
AR."ID_COLOR"= CL."ID_COLOR" AND
FM."CODIGO"='CALA' AND
MD."CODIGO" ='S'